// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: applications.sql

package pgdao

import (
	"context"
	"database/sql"
	"time"
)

const applicationAdd = `-- name: ApplicationAdd :one
insert into applications (
    id, "comment", price, job_id, applicant_id
) values (
    $1, $2, $3, $4, $5
)
returning id, created_at, updated_at, comment, price, job_id, applicant_id
`

type ApplicationAddParams struct {
	ID          string
	Comment     string
	Price       string
	JobID       string
	ApplicantID string
}

func (q *Queries) ApplicationAdd(ctx context.Context, arg ApplicationAddParams) (Application, error) {
	row := q.db.QueryRowContext(ctx, applicationAdd,
		arg.ID,
		arg.Comment,
		arg.Price,
		arg.JobID,
		arg.ApplicantID,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Comment,
		&i.Price,
		&i.JobID,
		&i.ApplicantID,
	)
	return i, err
}

const applicationFindByJobAndApplicant = `-- name: ApplicationFindByJobAndApplicant :one
select a.id, a.created_at, a.updated_at, a.comment, a.price, a.job_id, a.applicant_id
	, j.title AS job_title
	, j.budget AS job_budget
	, j.description AS job_description
	, c.id AS contract_id
	, c.status AS contract_status
	, (CASE WHEN p.display_name = '' THEN p.login ELSE p.display_name END)::varchar AS applicant_display_name
	, p.ethereum_address AS applicant_ethereum_address
	from applications a
	join persons p on p.id = a.applicant_id
	join jobs j on j.id = a.job_id
	left join contracts c on c.application_id  = a.id and c.performer_id = a.applicant_id
	where a.job_id = $1::varchar and a.applicant_id = $2::varchar
	limit 1
`

type ApplicationFindByJobAndApplicantParams struct {
	JobID       string
	ApplicantID string
}

type ApplicationFindByJobAndApplicantRow struct {
	ID                       string
	CreatedAt                time.Time
	UpdatedAt                time.Time
	Comment                  string
	Price                    string
	JobID                    string
	ApplicantID              string
	JobTitle                 string
	JobBudget                sql.NullString
	JobDescription           string
	ContractID               sql.NullString
	ContractStatus           sql.NullString
	ApplicantDisplayName     string
	ApplicantEthereumAddress string
}

func (q *Queries) ApplicationFindByJobAndApplicant(ctx context.Context, arg ApplicationFindByJobAndApplicantParams) (ApplicationFindByJobAndApplicantRow, error) {
	row := q.db.QueryRowContext(ctx, applicationFindByJobAndApplicant, arg.JobID, arg.ApplicantID)
	var i ApplicationFindByJobAndApplicantRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Comment,
		&i.Price,
		&i.JobID,
		&i.ApplicantID,
		&i.JobTitle,
		&i.JobBudget,
		&i.JobDescription,
		&i.ContractID,
		&i.ContractStatus,
		&i.ApplicantDisplayName,
		&i.ApplicantEthereumAddress,
	)
	return i, err
}

const applicationGet = `-- name: ApplicationGet :one
select a.id, a.created_at, a.updated_at, a.comment, a.price, a.job_id, a.applicant_id
	, j.title AS job_title
	, j.budget AS job_budget
	, j.description AS job_description
	, c.id AS contract_id
	, c.status AS contract_status
	, (CASE WHEN p.display_name = '' THEN p.login ELSE p.display_name END)::varchar AS applicant_display_name
	, p.ethereum_address AS applicant_ethereum_address
	from applications a
	join jobs j on j.id = a.job_id
	join persons p on p.id = a.applicant_id
	left join contracts c on c.application_id  = a.id and c.performer_id = a.applicant_id
	where a.id = $1::varchar
`

type ApplicationGetRow struct {
	ID                       string
	CreatedAt                time.Time
	UpdatedAt                time.Time
	Comment                  string
	Price                    string
	JobID                    string
	ApplicantID              string
	JobTitle                 string
	JobBudget                sql.NullString
	JobDescription           string
	ContractID               sql.NullString
	ContractStatus           sql.NullString
	ApplicantDisplayName     string
	ApplicantEthereumAddress string
}

func (q *Queries) ApplicationGet(ctx context.Context, id string) (ApplicationGetRow, error) {
	row := q.db.QueryRowContext(ctx, applicationGet, id)
	var i ApplicationGetRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Comment,
		&i.Price,
		&i.JobID,
		&i.ApplicantID,
		&i.JobTitle,
		&i.JobBudget,
		&i.JobDescription,
		&i.ContractID,
		&i.ContractStatus,
		&i.ApplicantDisplayName,
		&i.ApplicantEthereumAddress,
	)
	return i, err
}

const applicationsGetByApplicant = `-- name: ApplicationsGetByApplicant :many
select a.id, a.created_at, a.updated_at, a.comment, a.price, a.job_id, a.applicant_id
	, j.title AS job_title
	, j.budget AS job_budget
	, j.description AS job_description
	, c.id as contract_id
	, c.status as contract_status
	, c.price as contract_price
	, (CASE WHEN p.display_name = '' THEN p.login ELSE p.display_name END)::varchar AS applicant_display_name
	, p.ethereum_address AS applicant_ethereum_address
	from applications a
	join persons p on p.id = a.applicant_id
	join jobs j on a.job_id = j.id
	left join contracts c on a.id = c.application_id
	where a.applicant_id = $1::varchar
	order by a.created_at desc
`

type ApplicationsGetByApplicantRow struct {
	ID                       string
	CreatedAt                time.Time
	UpdatedAt                time.Time
	Comment                  string
	Price                    string
	JobID                    string
	ApplicantID              string
	JobTitle                 string
	JobBudget                sql.NullString
	JobDescription           string
	ContractID               sql.NullString
	ContractStatus           sql.NullString
	ContractPrice            sql.NullString
	ApplicantDisplayName     string
	ApplicantEthereumAddress string
}

func (q *Queries) ApplicationsGetByApplicant(ctx context.Context, applicantID string) ([]ApplicationsGetByApplicantRow, error) {
	rows, err := q.db.QueryContext(ctx, applicationsGetByApplicant, applicantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationsGetByApplicantRow
	for rows.Next() {
		var i ApplicationsGetByApplicantRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Comment,
			&i.Price,
			&i.JobID,
			&i.ApplicantID,
			&i.JobTitle,
			&i.JobBudget,
			&i.JobDescription,
			&i.ContractID,
			&i.ContractStatus,
			&i.ContractPrice,
			&i.ApplicantDisplayName,
			&i.ApplicantEthereumAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const applicationsGetByJob = `-- name: ApplicationsGetByJob :many
select a.id, a.created_at, a.updated_at, a.comment, a.price, a.job_id, a.applicant_id
	, c.id AS contract_id
	, c.status AS contract_status
	, (CASE WHEN p.display_name = '' THEN p.login ELSE p.display_name END)::varchar AS applicant_display_name
	, p.ethereum_address AS applicant_ethereum_address
	from applications a
	join persons p on p.id = a.applicant_id
	left join contracts c on c.application_id  = a.id and c.performer_id = a.applicant_id
	where a.job_id = $1::varchar
	order by a.created_at desc
`

type ApplicationsGetByJobRow struct {
	ID                       string
	CreatedAt                time.Time
	UpdatedAt                time.Time
	Comment                  string
	Price                    string
	JobID                    string
	ApplicantID              string
	ContractID               sql.NullString
	ContractStatus           sql.NullString
	ApplicantDisplayName     string
	ApplicantEthereumAddress string
}

func (q *Queries) ApplicationsGetByJob(ctx context.Context, jobID string) ([]ApplicationsGetByJobRow, error) {
	rows, err := q.db.QueryContext(ctx, applicationsGetByJob, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApplicationsGetByJobRow
	for rows.Next() {
		var i ApplicationsGetByJobRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Comment,
			&i.Price,
			&i.JobID,
			&i.ApplicantID,
			&i.ContractID,
			&i.ContractStatus,
			&i.ApplicantDisplayName,
			&i.ApplicantEthereumAddress,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const applicationsPurge = `-- name: ApplicationsPurge :exec
DELETE FROM applications
`

// Handle with care!
func (q *Queries) ApplicationsPurge(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, applicationsPurge)
	return err
}
