// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: jobs.sql

package pgdao

import (
	"context"
	"database/sql"
	"time"
)

const jobAdd = `-- name: JobAdd :one
insert into jobs (
    id, title, description, budget, duration, created_by
) values (
    $1, $2, $3, $4, $5, $6
) returning id, title, description, budget, duration, created_at, updated_at, created_by
`

type JobAddParams struct {
	ID          string
	Title       string
	Description string
	Budget      sql.NullString
	Duration    sql.NullInt32
	CreatedBy   string
}

func (q *Queries) JobAdd(ctx context.Context, arg JobAddParams) (Job, error) {
	row := q.db.QueryRowContext(ctx, jobAdd,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Budget,
		arg.Duration,
		arg.CreatedBy,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Budget,
		&i.Duration,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatedBy,
	)
	return i, err
}

const jobGet = `-- name: JobGet :one
select
    j.id
    ,j.title
    ,j.description
    ,j.budget
    ,j.duration
    ,j.created_at
    ,j.created_by
    ,j.updated_at
    ,(select count(*) from applications a where a.job_id = j.id) as application_count
    , COALESCE(p.display_name, p.login) AS customer_display_name
    from jobs j
    join persons p on p.id = j.created_by
    where j.id = $1::varchar
`

type JobGetRow struct {
	ID                  string
	Title               string
	Description         string
	Budget              sql.NullString
	Duration            sql.NullInt32
	CreatedAt           time.Time
	CreatedBy           string
	UpdatedAt           time.Time
	ApplicationCount    int64
	CustomerDisplayName string
}

func (q *Queries) JobGet(ctx context.Context, id string) (JobGetRow, error) {
	row := q.db.QueryRowContext(ctx, jobGet, id)
	var i JobGetRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Budget,
		&i.Duration,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.UpdatedAt,
		&i.ApplicationCount,
		&i.CustomerDisplayName,
	)
	return i, err
}

const jobsList = `-- name: JobsList :many
select
     j.id
    ,j.title
    ,j.description
    ,j.budget
    ,j.duration
    ,j.created_at
    ,j.created_by
    ,j.updated_at
    ,(select count(*) from applications a where a.job_id = j.id) as application_count
    from jobs j
    order by created_at desc
`

type JobsListRow struct {
	ID               string
	Title            string
	Description      string
	Budget           sql.NullString
	Duration         sql.NullInt32
	CreatedAt        time.Time
	CreatedBy        string
	UpdatedAt        time.Time
	ApplicationCount int64
}

func (q *Queries) JobsList(ctx context.Context) ([]JobsListRow, error) {
	rows, err := q.db.QueryContext(ctx, jobsList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobsListRow
	for rows.Next() {
		var i JobsListRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Budget,
			&i.Duration,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.UpdatedAt,
			&i.ApplicationCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const jobsPurge = `-- name: JobsPurge :exec
DELETE FROM jobs
`

// Handle with care!
func (q *Queries) JobsPurge(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, jobsPurge)
	return err
}
