// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package pgdao

import (
	"database/sql"
	"time"
)

// Applications for job offers
type Application struct {
	// PK
	ID string
	// Application timestamp. When application was created.
	CreationTs time.Time
	// Job offer
	JobID string
	// Potential performer
	ApplicantID string
}

// Job offer table
type Job struct {
	// PK
	ID string
	// Job title. Like "web site creation"
	Title string
	// Details about the job. May be long, long text
	Description string
	// Estimated cost of the job if any
	Budget sql.NullString
	// Estimated duration of the job in days if any
	Duration sql.NullInt32
	// Creation timestamp
	CreatedAt time.Time
	// Who created this job and should pay for it
	CreatedBy string
	// When the job was updated last time
	UpdatedAt time.Time
}

// Person who can pay, get or earn money
type Person struct {
	// PK
	ID string
	// Creation time
	CreatedAt time.Time
	// This person's cryptocurrency address
	Address string
}
