// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: stat.sql

package pgdao

import (
	"context"
	"time"
)

const statRegistrationsByDate = `-- name: StatRegistrationsByDate :many
select date_trunc('day', p.created_at)::date "day", count(*) registrations
from persons p
group by day
order by day
`

type StatRegistrationsByDateRow struct {
	Day           time.Time
	Registrations int64
}

func (q *Queries) StatRegistrationsByDate(ctx context.Context) ([]StatRegistrationsByDateRow, error) {
	rows, err := q.db.QueryContext(ctx, statRegistrationsByDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatRegistrationsByDateRow
	for rows.Next() {
		var i StatRegistrationsByDateRow
		if err := rows.Scan(&i.Day, &i.Registrations); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsGetContractsCount = `-- name: StatsGetContractsCount :one
select count(id) AS count
from contracts
`

func (q *Queries) StatsGetContractsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, statsGetContractsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const statsGetContractsVolume = `-- name: StatsGetContractsVolume :one
select coalesce(sum(price), 0)::decimal AS volume
from contracts
where status IN ('approved', 'completed')
`

func (q *Queries) StatsGetContractsVolume(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, statsGetContractsVolume)
	var volume string
	err := row.Scan(&volume)
	return volume, err
}

const statsGetOpenedJobsCount = `-- name: StatsGetOpenedJobsCount :one
select count(id) AS count
from jobs
where suspended_at is null and blocked_at is null
`

func (q *Queries) StatsGetOpenedJobsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, statsGetOpenedJobsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const statsGetRegistrationsCount = `-- name: StatsGetRegistrationsCount :one
select count(id) AS count
from persons
`

func (q *Queries) StatsGetRegistrationsCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, statsGetRegistrationsCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}
