// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package pgdao

import (
	"time"
)

// Applications for job offers
type Application struct {
	// PK
	ID string
	// Application timestamp. When application was created.
	CreationTs time.Time
	// Job offer
	JobID string
	// Potential performer
	ApplicantID string
}

// Job offer table
type Job struct {
	// PK
	ID string
	// Creation timestamp
	CreationTs time.Time
	// Job title. Like "web site creation"
	Title string
	// Details for these job. May be long, long text
	Description string
	// Who will pay this job
	CustomerID string
}

// Person who can pay, get or earn money
type Person struct {
	// PK
	ID string
	// This person's cryptocurrency address
	Address string
}
